# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: >-
      ^docs/[^/]*\.svg$
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-yaml
  - id: check-json
  - id: check-xml
  - id: check-toml
  - id: check-executables-have-shebangs
  - id: debug-statements
  - id: detect-private-key
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: check-symlinks
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args: ['--remove']
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.10.1'
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.10.0 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
    - id: black
      language_version: python3 # Should be a command that runs python3.6+
      args: ["--verbose", "--line-length=180"]
      exclude: 'src/presenter_drivers/gpio/bbb_pin_table.py'

- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.0
  hooks:
  - id: pyupgrade
    args: ['--py38-plus', '--keep-runtime-typing']

- repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  rev: v1.0.1
  hooks:
  - id: rst-linter
    files: >-
      ^[^/]+[.]rst$

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    exclude: "^docs/"
    additional_dependencies: [flake8-typing-imports==1.13.0]

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.0
  hooks:
  - id: autopep8
    exclude: 'src/presenter_drivers/gpio/bbb_pin_table.py'
#    args: ["-i", "-vvv"]

# - repo: https://github.com/asottile/reorder_python_imports
#   rev: v2.4.0
#   hooks:
#   - id: reorder-python-imports

#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v0.971
#  hooks:
#  - id: mypy
#    args: [-v]
#    additional_dependencies: ['typing-extensions', 'mypy-extensions', 'pytest']
#    exclude: "setup.py"
#    # Mypy in an existing environment
#    language: system
#    # use your preferred Python version
#    language_version: python3.7
#    # trigger for commits changing Python files
#    types: [python]
#    # use require_serial so that script
#    # is only called once per commit
#    require_serial: true
#    # print the number of files as a sanity-check
#    verbose: true

- repo: local # Hack to get pre-commit to run mypy. I did this because pre-commit's dependencies run in their own virtual env, and don't include mypy config
  hooks:
  - id: local-mypy
    name: Run mypy through venv
    language: system
    entry: make mypy
    pass_filenames: false
    types: [python]
    require_serial: true
    verbose: true
